# Generated by Django 5.2.1 on 2025-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Travel', 'Travel'), ('Food', 'Food'), ('Lifestyle', 'Lifestyle'), ('Business', 'Business'), ('Other', 'Other')], default='Technology', max_length=50),
        ),
    ]
